// <auto-generated />
namespace ControleFinanceiro1.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class required_campos : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(required_campos));
        
        string IMigrationMetadata.Id
        {
            get { return "201701231914467_required_campos"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
