// <auto-generated />
namespace ControleFinanceiro1.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class log_test4 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(log_test4));
        
        string IMigrationMetadata.Id
        {
            get { return "201701201854232_log_test4"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
