// <auto-generated />
namespace ControleFinanceiro1.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class valor_float2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(valor_float2));
        
        string IMigrationMetadata.Id
        {
            get { return "201701191311129_valor_float2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
